version: "3"
services:

  bm-wiki-db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: bm-wiki
      POSTGRES_PASSWORD: ${BM_WIKI_DB_PASS}
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  bm-wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - bm-wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: bm-wiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${BM_WIKI_DB_PASS}
      DB_NAME: bm-wiki
    restart: unless-stopped
    ports:
      - "8082:3000"

volumes:
  db-data: